### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lexer609** [akrambak/TikTok-OSINT#4]
content = json.loads(content[0].contents[0])
IndexError: list index out of range

**Comment by vidgix** [comment]
lol me to

**Comment by lexer609** [comment]
help

**Comment by vidgix** [comment]
alright i arleady know what is that indexerror so if u want to run this in windows 
u can change 

**content = json.loads(content[0].contents[3])**

bcz in the "type:" **content = soup.find_all("script", attrs={"type":"application/json", "crossorigin":"anonymous"})** 
have a 3 object i guess so have fun with ur stalker :)

**Comment by vidgix** [comment]
The error didn't appear, but it wasn't quick :(

**Comment by RunningTarg3t** [comment]
Hello, 
I use it with windows and got the same problem. I changed the number of contents, but without effort, same error:

Traceback (most recent call last):
  File "C:\Program Files\TikTOkOSINT-master\tiktokOSINT.py", line 126, in <module>
    main()
  File "C:\Program Files\TikTOkOSINT-master\tiktokOSINT.py", line 122, in main
    tiktok = TikTokOSINT(args.username[0])
  File "C:\Program Files\TikTOkOSINT-master\tiktokOSINT.py", line 32, in __init__
    self.data = self.scrape_profile()
  File "C:\Program Files\TikTOkOSINT-master\tiktokOSINT.py", line 48, in scrape_profile
    content = json.loads(content[0].contents[3])
IndexError: list index out of range

What may I do?

**Comment by andrew-pavlov-ua** [comment]
i have this problem too
